export const CampaignReward = [
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 8, RDG_Replay: 2 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 10, RDG_Replay: 3 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 12, RDG_Replay: 4 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 14, RDG_Replay: 5 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 16, RDG_Replay: 6 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 18, RDG_Replay: 7 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 20, RDG_Replay: 8 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 22, RDG_Replay: 9 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 24, RDG_Replay: 10 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 26, RDG_Replay: 11 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 28, RDG_Replay: 12 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 30, RDG_Replay: 13 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 32, RDG_Replay: 14 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 34, RDG_Replay: 15 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 36, RDG_Replay: 16 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 38, RDG_Replay: 17 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 40, RDG_Replay: 18 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 42, RDG_Replay: 19 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 44, RDG_Replay: 20 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 46, RDG_Replay: 21 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 48, RDG_Replay: 22 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 50, RDG_Replay: 23 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 52, RDG_Replay: 24 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 54, RDG_Replay: 25 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 56, RDG_Replay: 26 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 58, RDG_Replay: 27 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 60, RDG_Replay: 28 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 62, RDG_Replay: 29 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 64, RDG_Replay: 30 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 66, RDG_Replay: 31 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 68, RDG_Replay: 32 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 70, RDG_Replay: 33 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 72, RDG_Replay: 34 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 74, RDG_Replay: 35 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 76, RDG_Replay: 36 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 78, RDG_Replay: 37 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 80, RDG_Replay: 38 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 82, RDG_Replay: 39 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 84, RDG_Replay: 40 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 86, RDG_Replay: 41 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 88, RDG_Replay: 42 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 90, RDG_Replay: 43 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 92, RDG_Replay: 44 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 94, RDG_Replay: 45 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 96, RDG_Replay: 46 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 98, RDG_Replay: 47 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 100, RDG_Replay: 48 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 102, RDG_Replay: 49 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 104, RDG_Replay: 50 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 106, RDG_Replay: 51 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 108, RDG_Replay: 52 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 110, RDG_Replay: 53 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 112, RDG_Replay: 54 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 114, RDG_Replay: 55 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 116, RDG_Replay: 56 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 118, RDG_Replay: 57 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 120, RDG_Replay: 58 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 122, RDG_Replay: 59 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 124, RDG_Replay: 60 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 126, RDG_Replay: 61 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 128, RDG_Replay: 62 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 130, RDG_Replay: 63 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 132, RDG_Replay: 64 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 134, RDG_Replay: 65 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 136, RDG_Replay: 66 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 138, RDG_Replay: 67 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 140, RDG_Replay: 68 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 142, RDG_Replay: 69 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 144, RDG_Replay: 70 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 146, RDG_Replay: 71 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 148, RDG_Replay: 72 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 150, RDG_Replay: 73 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 152, RDG_Replay: 74 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 154, RDG_Replay: 75 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 156, RDG_Replay: 76 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 158, RDG_Replay: 77 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 160, RDG_Replay: 78 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 162, RDG_Replay: 79 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 164, RDG_Replay: 80 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 166, RDG_Replay: 81 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 168, RDG_Replay: 82 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 170, RDG_Replay: 83 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 172, RDG_Replay: 84 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 174, RDG_Replay: 85 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 176, RDG_Replay: 86 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 178, RDG_Replay: 87 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 180, RDG_Replay: 88 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 182, RDG_Replay: 89 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 184, RDG_Replay: 90 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 186, RDG_Replay: 91 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 188, RDG_Replay: 92 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 190, RDG_Replay: 93 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 192, RDG_Replay: 94 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 194, RDG_Replay: 95 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 196, RDG_Replay: 96 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 198, RDG_Replay: 97 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 200, RDG_Replay: 98 },
    { BoxClearRate: 0, BoxReplayRate: 0, RDG_Clear: 202, RDG_Replay: 99 },
    {
      BoxClearRate: 0,
      BoxReplayRate: 0,
      RDG_Clear: 204,
      RDG_Replay: 100
    },
    {
      BoxClearRate: 0,
      BoxReplayRate: 0,
      RDG_Clear: 206,
      RDG_Replay: 101
    }
  ]